version: '3'

includes:
    default: .tk/default/Taskfile.yaml
    git: .tk/git/Taskfile.yaml
    golangci: .tk/golangci/Taskfile.yaml
    install: .tk/install/Taskfile.yaml
    license: .tk/license/Taskfile.yaml
    trufflehog: .tk/trufflehog/Taskfile.yaml


dotenv:
  - .env
  - PROJECT
  - .env.default

tasks:
  test:
    desc: Run unit tests with the race detector.
    cmds:
      - go test -race ./...

  clean:
    desc: Remove build artifacts and clear the test cache.
    cmds:
      - rm -rf bin dist
      - go clean -testcache