// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file v1/daemon.proto (package openotters.daemon.v1, syntax proto3)
/* eslint-disable */

import { Runtime } from "./daemon_pb";

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetInfo
 */
export const getInfo = Runtime.method.getInfo;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.BuildAgent
 */
export const buildAgent = Runtime.method.buildAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.BuildToolImage
 */
export const buildToolImage = Runtime.method.buildToolImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.SaveAgentImage
 */
export const saveAgentImage = Runtime.method.saveAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PullAgentImage
 */
export const pullAgentImage = Runtime.method.pullAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PushAgentImage
 */
export const pushAgentImage = Runtime.method.pushAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListImages
 */
export const listImages = Runtime.method.listImages;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RefreshImage
 */
export const refreshImage = Runtime.method.refreshImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveImage
 */
export const removeImage = Runtime.method.removeImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.DescribeImage
 */
export const describeImage = Runtime.method.describeImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.CreateAgent
 */
export const createAgent = Runtime.method.createAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListAgents
 */
export const listAgents = Runtime.method.listAgents;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.StartAgent
 */
export const startAgent = Runtime.method.startAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.StopAgent
 */
export const stopAgent = Runtime.method.stopAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveAgent
 */
export const removeAgent = Runtime.method.removeAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ChatWithAgent
 */
export const chatWithAgent = Runtime.method.chatWithAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PromptObject
 */
export const promptObject = Runtime.method.promptObject;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListSessionMessages
 */
export const listSessionMessages = Runtime.method.listSessionMessages;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetAgentLogs
 */
export const getAgentLogs = Runtime.method.getAgentLogs;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListModels
 */
export const listModels = Runtime.method.listModels;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListProviders
 */
export const listProviders = Runtime.method.listProviders;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.AddProvider
 */
export const addProvider = Runtime.method.addProvider;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.UpdateProvider
 */
export const updateProvider = Runtime.method.updateProvider;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveProvider
 */
export const removeProvider = Runtime.method.removeProvider;
