// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file v1/daemon.proto (package openotters.daemon.v1, syntax proto3)
/* eslint-disable */

import { Runtime } from "./daemon_pb";

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetInfo
 */
export const getInfo = Runtime.method.getInfo;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.BuildAgent
 */
export const buildAgent = Runtime.method.buildAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.BuildToolImage
 */
export const buildToolImage = Runtime.method.buildToolImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.SaveAgentImage
 */
export const saveAgentImage = Runtime.method.saveAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PullAgentImage
 */
export const pullAgentImage = Runtime.method.pullAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PushAgentImage
 */
export const pushAgentImage = Runtime.method.pushAgentImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListImages
 */
export const listImages = Runtime.method.listImages;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RefreshImage
 */
export const refreshImage = Runtime.method.refreshImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveImage
 */
export const removeImage = Runtime.method.removeImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.DescribeImage
 */
export const describeImage = Runtime.method.describeImage;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.CreateAgent
 */
export const createAgent = Runtime.method.createAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListAgents
 */
export const listAgents = Runtime.method.listAgents;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.StartAgent
 */
export const startAgent = Runtime.method.startAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.StopAgent
 */
export const stopAgent = Runtime.method.stopAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveAgent
 */
export const removeAgent = Runtime.method.removeAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ChatWithAgent
 */
export const chatWithAgent = Runtime.method.chatWithAgent;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.PromptObject
 */
export const promptObject = Runtime.method.promptObject;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListSessionMessages
 */
export const listSessionMessages = Runtime.method.listSessionMessages;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListSessions
 */
export const listSessions = Runtime.method.listSessions;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.DeleteSession
 */
export const deleteSession = Runtime.method.deleteSession;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetAgentLogs
 */
export const getAgentLogs = Runtime.method.getAgentLogs;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListModels
 */
export const listModels = Runtime.method.listModels;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListProviders
 */
export const listProviders = Runtime.method.listProviders;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.AddProvider
 */
export const addProvider = Runtime.method.addProvider;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.UpdateProvider
 */
export const updateProvider = Runtime.method.updateProvider;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.RemoveProvider
 */
export const removeProvider = Runtime.method.removeProvider;

/**
 * ── async jobs ────────────────────────────────────────────────────
 * Submit a BIN job to run against the agent's spawn env. Jobs are
 * attached to the agent — not to a session. The daemon does not
 * push results anywhere on completion: observers (agent runtime,
 * operator CLI, UI) read via GetAsyncJob / WatchAsyncJob and
 * decide their own watch strategy.
 *
 * @generated from rpc openotters.daemon.v1.Runtime.SubmitAsyncJob
 */
export const submitAsyncJob = Runtime.method.submitAsyncJob;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.CancelAsyncJob
 */
export const cancelAsyncJob = Runtime.method.cancelAsyncJob;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetAsyncJob
 */
export const getAsyncJob = Runtime.method.getAsyncJob;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListAsyncJobs
 */
export const listAsyncJobs = Runtime.method.listAsyncJobs;

/**
 * ── notes (per-agent KV store) ───────────────────────────────────
 * Operator-facing CRUD for an agent's notes (durable facts the
 * model wrote via the note_* tools). Each RPC proxies to the per-
 * agent runtime's gRPC NotesService and surfaces NotFound /
 * FailedPrecondition cleanly to the UI.
 *
 * @generated from rpc openotters.daemon.v1.Runtime.ListAgentNotes
 */
export const listAgentNotes = Runtime.method.listAgentNotes;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.GetAgentNote
 */
export const getAgentNote = Runtime.method.getAgentNote;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.SaveAgentNote
 */
export const saveAgentNote = Runtime.method.saveAgentNote;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.DeleteAgentNote
 */
export const deleteAgentNote = Runtime.method.deleteAgentNote;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.SetAgentNoteInContext
 */
export const setAgentNoteInContext = Runtime.method.setAgentNoteInContext;

/**
 * ── agent linking ───────────────────────────────────────────────
 * Operator-facing CRUD for the directed agent → agent call graph.
 * `otters link / unlink / links` map 1:1 to these RPCs. Auto-
 * restart of the source agent happens server-side on every
 * mutating call so the JWT (which carries the authoritative link
 * set) is always fresh.
 *
 * @generated from rpc openotters.daemon.v1.Runtime.LinkAgents
 */
export const linkAgents = Runtime.method.linkAgents;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.UnlinkAgents
 */
export const unlinkAgents = Runtime.method.unlinkAgents;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.ListAgentLinks
 */
export const listAgentLinks = Runtime.method.listAgentLinks;

/**
 * Agent-facing cross-agent RPCs. Caller must present an agent
 * token; target must be in the JWT's Links claim. Enforced by
 * the AgentLinkedInterceptor wrapping these four handlers.
 *
 * @generated from rpc openotters.daemon.v1.Runtime.AgentList
 */
export const agentList = Runtime.method.agentList;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.AgentInfo
 */
export const agentInfo = Runtime.method.agentInfo;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.AgentChat
 */
export const agentChat = Runtime.method.agentChat;

/**
 * @generated from rpc openotters.daemon.v1.Runtime.AgentExec
 */
export const agentExec = Runtime.method.agentExec;
