// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file v1/daemon.proto (package openotters.daemon.v1, syntax proto3)
/* eslint-disable */

import { AgentState } from "./daemon_pb";

/**
 * Messages — chat history + branches.
 *
 * @generated from rpc openotters.daemon.v1.AgentState.ListMessages
 */
export const listMessages = AgentState.method.listMessages;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.AppendMessage
 */
export const appendMessage = AgentState.method.appendMessage;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.ReplaceMessages
 */
export const replaceMessages = AgentState.method.replaceMessages;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.UpdateMessageBranches
 */
export const updateMessageBranches = AgentState.method.updateMessageBranches;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.LastAssistantMessage
 */
export const lastAssistantMessage = AgentState.method.lastAssistantMessage;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.CountMessages
 */
export const countMessages = AgentState.method.countMessages;

/**
 * Sessions — derived from messages (no separate table).
 *
 * @generated from rpc openotters.daemon.v1.AgentState.ListSessions
 */
export const listSessions = AgentState.method.listSessions;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.DeleteSession
 */
export const deleteSession = AgentState.method.deleteSession;

/**
 * Notes — the per-agent KV.
 *
 * @generated from rpc openotters.daemon.v1.AgentState.ListNotes
 */
export const listNotes = AgentState.method.listNotes;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.GetNote
 */
export const getNote = AgentState.method.getNote;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.SaveNote
 */
export const saveNote = AgentState.method.saveNote;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.DeleteNote
 */
export const deleteNote = AgentState.method.deleteNote;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.SetNoteInContext
 */
export const setNoteInContext = AgentState.method.setNoteInContext;

/**
 * @generated from rpc openotters.daemon.v1.AgentState.CountNotes
 */
export const countNotes = AgentState.method.countNotes;
