// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/daemon.proto

package daemonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_GetInfo_FullMethodName               = "/openotters.daemon.v1.Runtime/GetInfo"
	Runtime_BuildAgent_FullMethodName            = "/openotters.daemon.v1.Runtime/BuildAgent"
	Runtime_BuildToolImage_FullMethodName        = "/openotters.daemon.v1.Runtime/BuildToolImage"
	Runtime_SaveAgentImage_FullMethodName        = "/openotters.daemon.v1.Runtime/SaveAgentImage"
	Runtime_PullAgentImage_FullMethodName        = "/openotters.daemon.v1.Runtime/PullAgentImage"
	Runtime_PushAgentImage_FullMethodName        = "/openotters.daemon.v1.Runtime/PushAgentImage"
	Runtime_ListImages_FullMethodName            = "/openotters.daemon.v1.Runtime/ListImages"
	Runtime_RefreshImage_FullMethodName          = "/openotters.daemon.v1.Runtime/RefreshImage"
	Runtime_RemoveImage_FullMethodName           = "/openotters.daemon.v1.Runtime/RemoveImage"
	Runtime_DescribeImage_FullMethodName         = "/openotters.daemon.v1.Runtime/DescribeImage"
	Runtime_CreateAgent_FullMethodName           = "/openotters.daemon.v1.Runtime/CreateAgent"
	Runtime_ListAgents_FullMethodName            = "/openotters.daemon.v1.Runtime/ListAgents"
	Runtime_StartAgent_FullMethodName            = "/openotters.daemon.v1.Runtime/StartAgent"
	Runtime_StopAgent_FullMethodName             = "/openotters.daemon.v1.Runtime/StopAgent"
	Runtime_RemoveAgent_FullMethodName           = "/openotters.daemon.v1.Runtime/RemoveAgent"
	Runtime_ChatWithAgent_FullMethodName         = "/openotters.daemon.v1.Runtime/ChatWithAgent"
	Runtime_PromptObject_FullMethodName          = "/openotters.daemon.v1.Runtime/PromptObject"
	Runtime_ChatStreamWithAgent_FullMethodName   = "/openotters.daemon.v1.Runtime/ChatStreamWithAgent"
	Runtime_ListSessionMessages_FullMethodName   = "/openotters.daemon.v1.Runtime/ListSessionMessages"
	Runtime_ListSessions_FullMethodName          = "/openotters.daemon.v1.Runtime/ListSessions"
	Runtime_DeleteSession_FullMethodName         = "/openotters.daemon.v1.Runtime/DeleteSession"
	Runtime_GetAgentLogs_FullMethodName          = "/openotters.daemon.v1.Runtime/GetAgentLogs"
	Runtime_ListModels_FullMethodName            = "/openotters.daemon.v1.Runtime/ListModels"
	Runtime_ListProviders_FullMethodName         = "/openotters.daemon.v1.Runtime/ListProviders"
	Runtime_AddProvider_FullMethodName           = "/openotters.daemon.v1.Runtime/AddProvider"
	Runtime_UpdateProvider_FullMethodName        = "/openotters.daemon.v1.Runtime/UpdateProvider"
	Runtime_RemoveProvider_FullMethodName        = "/openotters.daemon.v1.Runtime/RemoveProvider"
	Runtime_SubmitAsyncJob_FullMethodName        = "/openotters.daemon.v1.Runtime/SubmitAsyncJob"
	Runtime_CancelAsyncJob_FullMethodName        = "/openotters.daemon.v1.Runtime/CancelAsyncJob"
	Runtime_GetAsyncJob_FullMethodName           = "/openotters.daemon.v1.Runtime/GetAsyncJob"
	Runtime_ListAsyncJobs_FullMethodName         = "/openotters.daemon.v1.Runtime/ListAsyncJobs"
	Runtime_ListAgentNotes_FullMethodName        = "/openotters.daemon.v1.Runtime/ListAgentNotes"
	Runtime_GetAgentNote_FullMethodName          = "/openotters.daemon.v1.Runtime/GetAgentNote"
	Runtime_SaveAgentNote_FullMethodName         = "/openotters.daemon.v1.Runtime/SaveAgentNote"
	Runtime_DeleteAgentNote_FullMethodName       = "/openotters.daemon.v1.Runtime/DeleteAgentNote"
	Runtime_SetAgentNoteInContext_FullMethodName = "/openotters.daemon.v1.Runtime/SetAgentNoteInContext"
	Runtime_WatchAsyncJob_FullMethodName         = "/openotters.daemon.v1.Runtime/WatchAsyncJob"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	BuildAgent(ctx context.Context, in *BuildAgentRequest, opts ...grpc.CallOption) (*BuildAgentResponse, error)
	BuildToolImage(ctx context.Context, in *BuildToolImageRequest, opts ...grpc.CallOption) (*BuildToolImageResponse, error)
	SaveAgentImage(ctx context.Context, in *SaveAgentImageRequest, opts ...grpc.CallOption) (*SaveAgentImageResponse, error)
	PullAgentImage(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	PushAgentImage(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	RefreshImage(ctx context.Context, in *RefreshImageRequest, opts ...grpc.CallOption) (*RefreshImageResponse, error)
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	DescribeImage(ctx context.Context, in *DescribeImageRequest, opts ...grpc.CallOption) (*DescribeImageResponse, error)
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*StartAgentResponse, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentResponse, error)
	RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error)
	ChatWithAgent(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	PromptObject(ctx context.Context, in *PromptObjectRequest, opts ...grpc.CallOption) (*PromptObjectResponse, error)
	ChatStreamWithAgent(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamEvent], error)
	ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	GetAgentLogs(ctx context.Context, in *GetAgentLogsRequest, opts ...grpc.CallOption) (*GetAgentLogsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	AddProvider(ctx context.Context, in *AddProviderRequest, opts ...grpc.CallOption) (*AddProviderResponse, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error)
	RemoveProvider(ctx context.Context, in *RemoveProviderRequest, opts ...grpc.CallOption) (*RemoveProviderResponse, error)
	// ── async jobs ────────────────────────────────────────────────────
	// Submit a BIN job to run against the agent's spawn env. Jobs are
	// attached to the agent — not to a session. The daemon does not
	// push results anywhere on completion: observers (agent runtime,
	// operator CLI, UI) read via GetAsyncJob / WatchAsyncJob and
	// decide their own watch strategy.
	SubmitAsyncJob(ctx context.Context, in *SubmitAsyncJobRequest, opts ...grpc.CallOption) (*SubmitAsyncJobResponse, error)
	CancelAsyncJob(ctx context.Context, in *CancelAsyncJobRequest, opts ...grpc.CallOption) (*CancelAsyncJobResponse, error)
	GetAsyncJob(ctx context.Context, in *GetAsyncJobRequest, opts ...grpc.CallOption) (*GetAsyncJobResponse, error)
	ListAsyncJobs(ctx context.Context, in *ListAsyncJobsRequest, opts ...grpc.CallOption) (*ListAsyncJobsResponse, error)
	// ── notes (per-agent KV store) ───────────────────────────────────
	// Operator-facing CRUD for an agent's notes (durable facts the
	// model wrote via the note_* tools). Each RPC proxies to the per-
	// agent runtime's gRPC NotesService and surfaces NotFound /
	// FailedPrecondition cleanly to the UI.
	ListAgentNotes(ctx context.Context, in *ListAgentNotesRequest, opts ...grpc.CallOption) (*ListAgentNotesResponse, error)
	GetAgentNote(ctx context.Context, in *GetAgentNoteRequest, opts ...grpc.CallOption) (*GetAgentNoteResponse, error)
	SaveAgentNote(ctx context.Context, in *SaveAgentNoteRequest, opts ...grpc.CallOption) (*SaveAgentNoteResponse, error)
	DeleteAgentNote(ctx context.Context, in *DeleteAgentNoteRequest, opts ...grpc.CallOption) (*DeleteAgentNoteResponse, error)
	SetAgentNoteInContext(ctx context.Context, in *SetAgentNoteInContextRequest, opts ...grpc.CallOption) (*SetAgentNoteInContextResponse, error)
	// Server-streaming watch: emits the current AsyncJob immediately,
	// then again on every material change (status, handle, exit_code,
	// stdout, stderr, error, started_at, finished_at), then closes the
	// stream when the job reaches a terminal status. NotFound at start
	// when the job doesn't exist. Implemented as a server-side poll
	// (~250 ms) — observers see at most ~250 ms latency from a status
	// flip to the corresponding stream message.
	WatchAsyncJob(ctx context.Context, in *WatchAsyncJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAsyncJobResponse], error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, Runtime_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) BuildAgent(ctx context.Context, in *BuildAgentRequest, opts ...grpc.CallOption) (*BuildAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildAgentResponse)
	err := c.cc.Invoke(ctx, Runtime_BuildAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) BuildToolImage(ctx context.Context, in *BuildToolImageRequest, opts ...grpc.CallOption) (*BuildToolImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildToolImageResponse)
	err := c.cc.Invoke(ctx, Runtime_BuildToolImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) SaveAgentImage(ctx context.Context, in *SaveAgentImageRequest, opts ...grpc.CallOption) (*SaveAgentImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAgentImageResponse)
	err := c.cc.Invoke(ctx, Runtime_SaveAgentImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PullAgentImage(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, Runtime_PullAgentImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PushAgentImage(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, Runtime_PushAgentImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Runtime_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RefreshImage(ctx context.Context, in *RefreshImageRequest, opts ...grpc.CallOption) (*RefreshImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshImageResponse)
	err := c.cc.Invoke(ctx, Runtime_RefreshImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DescribeImage(ctx context.Context, in *DescribeImageRequest, opts ...grpc.CallOption) (*DescribeImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeImageResponse)
	err := c.cc.Invoke(ctx, Runtime_DescribeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, Runtime_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*StartAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAgentResponse)
	err := c.cc.Invoke(ctx, Runtime_StartAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAgentResponse)
	err := c.cc.Invoke(ctx, Runtime_StopAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAgentResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ChatWithAgent(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, Runtime_ChatWithAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PromptObject(ctx context.Context, in *PromptObjectRequest, opts ...grpc.CallOption) (*PromptObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptObjectResponse)
	err := c.cc.Invoke(ctx, Runtime_PromptObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ChatStreamWithAgent(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_ChatStreamWithAgent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatStreamRequest, ChatStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ChatStreamWithAgentClient = grpc.ServerStreamingClient[ChatStreamEvent]

func (c *runtimeClient) ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionMessagesResponse)
	err := c.cc.Invoke(ctx, Runtime_ListSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, Runtime_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetAgentLogs(ctx context.Context, in *GetAgentLogsRequest, opts ...grpc.CallOption) (*GetAgentLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentLogsResponse)
	err := c.cc.Invoke(ctx, Runtime_GetAgentLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, Runtime_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) AddProvider(ctx context.Context, in *AddProviderRequest, opts ...grpc.CallOption) (*AddProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProviderResponse)
	err := c.cc.Invoke(ctx, Runtime_AddProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderResponse)
	err := c.cc.Invoke(ctx, Runtime_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveProvider(ctx context.Context, in *RemoveProviderRequest, opts ...grpc.CallOption) (*RemoveProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveProviderResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) SubmitAsyncJob(ctx context.Context, in *SubmitAsyncJobRequest, opts ...grpc.CallOption) (*SubmitAsyncJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAsyncJobResponse)
	err := c.cc.Invoke(ctx, Runtime_SubmitAsyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CancelAsyncJob(ctx context.Context, in *CancelAsyncJobRequest, opts ...grpc.CallOption) (*CancelAsyncJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAsyncJobResponse)
	err := c.cc.Invoke(ctx, Runtime_CancelAsyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetAsyncJob(ctx context.Context, in *GetAsyncJobRequest, opts ...grpc.CallOption) (*GetAsyncJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAsyncJobResponse)
	err := c.cc.Invoke(ctx, Runtime_GetAsyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListAsyncJobs(ctx context.Context, in *ListAsyncJobsRequest, opts ...grpc.CallOption) (*ListAsyncJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAsyncJobsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListAsyncJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListAgentNotes(ctx context.Context, in *ListAgentNotesRequest, opts ...grpc.CallOption) (*ListAgentNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentNotesResponse)
	err := c.cc.Invoke(ctx, Runtime_ListAgentNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetAgentNote(ctx context.Context, in *GetAgentNoteRequest, opts ...grpc.CallOption) (*GetAgentNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentNoteResponse)
	err := c.cc.Invoke(ctx, Runtime_GetAgentNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) SaveAgentNote(ctx context.Context, in *SaveAgentNoteRequest, opts ...grpc.CallOption) (*SaveAgentNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAgentNoteResponse)
	err := c.cc.Invoke(ctx, Runtime_SaveAgentNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DeleteAgentNote(ctx context.Context, in *DeleteAgentNoteRequest, opts ...grpc.CallOption) (*DeleteAgentNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentNoteResponse)
	err := c.cc.Invoke(ctx, Runtime_DeleteAgentNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) SetAgentNoteInContext(ctx context.Context, in *SetAgentNoteInContextRequest, opts ...grpc.CallOption) (*SetAgentNoteInContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAgentNoteInContextResponse)
	err := c.cc.Invoke(ctx, Runtime_SetAgentNoteInContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) WatchAsyncJob(ctx context.Context, in *WatchAsyncJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAsyncJobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[1], Runtime_WatchAsyncJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchAsyncJobRequest, WatchAsyncJobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchAsyncJobClient = grpc.ServerStreamingClient[WatchAsyncJobResponse]

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	BuildAgent(context.Context, *BuildAgentRequest) (*BuildAgentResponse, error)
	BuildToolImage(context.Context, *BuildToolImageRequest) (*BuildToolImageResponse, error)
	SaveAgentImage(context.Context, *SaveAgentImageRequest) (*SaveAgentImageResponse, error)
	PullAgentImage(context.Context, *PullRequest) (*PullResponse, error)
	PushAgentImage(context.Context, *PushRequest) (*PushResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	RefreshImage(context.Context, *RefreshImageRequest) (*RefreshImageResponse, error)
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	DescribeImage(context.Context, *DescribeImageRequest) (*DescribeImageResponse, error)
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	StartAgent(context.Context, *StartAgentRequest) (*StartAgentResponse, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentResponse, error)
	RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error)
	ChatWithAgent(context.Context, *ChatRequest) (*ChatResponse, error)
	PromptObject(context.Context, *PromptObjectRequest) (*PromptObjectResponse, error)
	ChatStreamWithAgent(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamEvent]) error
	ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	GetAgentLogs(context.Context, *GetAgentLogsRequest) (*GetAgentLogsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	AddProvider(context.Context, *AddProviderRequest) (*AddProviderResponse, error)
	UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error)
	RemoveProvider(context.Context, *RemoveProviderRequest) (*RemoveProviderResponse, error)
	// ── async jobs ────────────────────────────────────────────────────
	// Submit a BIN job to run against the agent's spawn env. Jobs are
	// attached to the agent — not to a session. The daemon does not
	// push results anywhere on completion: observers (agent runtime,
	// operator CLI, UI) read via GetAsyncJob / WatchAsyncJob and
	// decide their own watch strategy.
	SubmitAsyncJob(context.Context, *SubmitAsyncJobRequest) (*SubmitAsyncJobResponse, error)
	CancelAsyncJob(context.Context, *CancelAsyncJobRequest) (*CancelAsyncJobResponse, error)
	GetAsyncJob(context.Context, *GetAsyncJobRequest) (*GetAsyncJobResponse, error)
	ListAsyncJobs(context.Context, *ListAsyncJobsRequest) (*ListAsyncJobsResponse, error)
	// ── notes (per-agent KV store) ───────────────────────────────────
	// Operator-facing CRUD for an agent's notes (durable facts the
	// model wrote via the note_* tools). Each RPC proxies to the per-
	// agent runtime's gRPC NotesService and surfaces NotFound /
	// FailedPrecondition cleanly to the UI.
	ListAgentNotes(context.Context, *ListAgentNotesRequest) (*ListAgentNotesResponse, error)
	GetAgentNote(context.Context, *GetAgentNoteRequest) (*GetAgentNoteResponse, error)
	SaveAgentNote(context.Context, *SaveAgentNoteRequest) (*SaveAgentNoteResponse, error)
	DeleteAgentNote(context.Context, *DeleteAgentNoteRequest) (*DeleteAgentNoteResponse, error)
	SetAgentNoteInContext(context.Context, *SetAgentNoteInContextRequest) (*SetAgentNoteInContextResponse, error)
	// Server-streaming watch: emits the current AsyncJob immediately,
	// then again on every material change (status, handle, exit_code,
	// stdout, stderr, error, started_at, finished_at), then closes the
	// stream when the job reaches a terminal status. NotFound at start
	// when the job doesn't exist. Implemented as a server-side poll
	// (~250 ms) — observers see at most ~250 ms latency from a status
	// flip to the corresponding stream message.
	WatchAsyncJob(*WatchAsyncJobRequest, grpc.ServerStreamingServer[WatchAsyncJobResponse]) error
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedRuntimeServer) BuildAgent(context.Context, *BuildAgentRequest) (*BuildAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildAgent not implemented")
}
func (UnimplementedRuntimeServer) BuildToolImage(context.Context, *BuildToolImageRequest) (*BuildToolImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildToolImage not implemented")
}
func (UnimplementedRuntimeServer) SaveAgentImage(context.Context, *SaveAgentImageRequest) (*SaveAgentImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAgentImage not implemented")
}
func (UnimplementedRuntimeServer) PullAgentImage(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullAgentImage not implemented")
}
func (UnimplementedRuntimeServer) PushAgentImage(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushAgentImage not implemented")
}
func (UnimplementedRuntimeServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedRuntimeServer) RefreshImage(context.Context, *RefreshImageRequest) (*RefreshImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshImage not implemented")
}
func (UnimplementedRuntimeServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedRuntimeServer) DescribeImage(context.Context, *DescribeImageRequest) (*DescribeImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeImage not implemented")
}
func (UnimplementedRuntimeServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedRuntimeServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedRuntimeServer) StartAgent(context.Context, *StartAgentRequest) (*StartAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAgent not implemented")
}
func (UnimplementedRuntimeServer) StopAgent(context.Context, *StopAgentRequest) (*StopAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAgent not implemented")
}
func (UnimplementedRuntimeServer) RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAgent not implemented")
}
func (UnimplementedRuntimeServer) ChatWithAgent(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatWithAgent not implemented")
}
func (UnimplementedRuntimeServer) PromptObject(context.Context, *PromptObjectRequest) (*PromptObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromptObject not implemented")
}
func (UnimplementedRuntimeServer) ChatStreamWithAgent(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStreamWithAgent not implemented")
}
func (UnimplementedRuntimeServer) ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionMessages not implemented")
}
func (UnimplementedRuntimeServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRuntimeServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedRuntimeServer) GetAgentLogs(context.Context, *GetAgentLogsRequest) (*GetAgentLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentLogs not implemented")
}
func (UnimplementedRuntimeServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedRuntimeServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedRuntimeServer) AddProvider(context.Context, *AddProviderRequest) (*AddProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProvider not implemented")
}
func (UnimplementedRuntimeServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedRuntimeServer) RemoveProvider(context.Context, *RemoveProviderRequest) (*RemoveProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProvider not implemented")
}
func (UnimplementedRuntimeServer) SubmitAsyncJob(context.Context, *SubmitAsyncJobRequest) (*SubmitAsyncJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAsyncJob not implemented")
}
func (UnimplementedRuntimeServer) CancelAsyncJob(context.Context, *CancelAsyncJobRequest) (*CancelAsyncJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAsyncJob not implemented")
}
func (UnimplementedRuntimeServer) GetAsyncJob(context.Context, *GetAsyncJobRequest) (*GetAsyncJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAsyncJob not implemented")
}
func (UnimplementedRuntimeServer) ListAsyncJobs(context.Context, *ListAsyncJobsRequest) (*ListAsyncJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAsyncJobs not implemented")
}
func (UnimplementedRuntimeServer) ListAgentNotes(context.Context, *ListAgentNotesRequest) (*ListAgentNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentNotes not implemented")
}
func (UnimplementedRuntimeServer) GetAgentNote(context.Context, *GetAgentNoteRequest) (*GetAgentNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentNote not implemented")
}
func (UnimplementedRuntimeServer) SaveAgentNote(context.Context, *SaveAgentNoteRequest) (*SaveAgentNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAgentNote not implemented")
}
func (UnimplementedRuntimeServer) DeleteAgentNote(context.Context, *DeleteAgentNoteRequest) (*DeleteAgentNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentNote not implemented")
}
func (UnimplementedRuntimeServer) SetAgentNoteInContext(context.Context, *SetAgentNoteInContextRequest) (*SetAgentNoteInContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentNoteInContext not implemented")
}
func (UnimplementedRuntimeServer) WatchAsyncJob(*WatchAsyncJobRequest, grpc.ServerStreamingServer[WatchAsyncJobResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchAsyncJob not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_BuildAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).BuildAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_BuildAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).BuildAgent(ctx, req.(*BuildAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_BuildToolImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildToolImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).BuildToolImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_BuildToolImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).BuildToolImage(ctx, req.(*BuildToolImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_SaveAgentImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAgentImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).SaveAgentImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_SaveAgentImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).SaveAgentImage(ctx, req.(*SaveAgentImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PullAgentImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PullAgentImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PullAgentImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PullAgentImage(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PushAgentImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PushAgentImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PushAgentImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PushAgentImage(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RefreshImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RefreshImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RefreshImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RefreshImage(ctx, req.(*RefreshImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DescribeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DescribeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DescribeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DescribeImage(ctx, req.(*DescribeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StartAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StartAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StartAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StartAgent(ctx, req.(*StartAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StopAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveAgent(ctx, req.(*RemoveAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ChatWithAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ChatWithAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ChatWithAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ChatWithAgent(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PromptObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PromptObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PromptObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PromptObject(ctx, req.(*PromptObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ChatStreamWithAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).ChatStreamWithAgent(m, &grpc.GenericServerStream[ChatStreamRequest, ChatStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ChatStreamWithAgentServer = grpc.ServerStreamingServer[ChatStreamEvent]

func _Runtime_ListSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListSessionMessages(ctx, req.(*ListSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetAgentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetAgentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetAgentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetAgentLogs(ctx, req.(*GetAgentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_AddProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).AddProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_AddProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).AddProvider(ctx, req.(*AddProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveProvider(ctx, req.(*RemoveProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_SubmitAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAsyncJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).SubmitAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_SubmitAsyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).SubmitAsyncJob(ctx, req.(*SubmitAsyncJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CancelAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAsyncJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CancelAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CancelAsyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CancelAsyncJob(ctx, req.(*CancelAsyncJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAsyncJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetAsyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetAsyncJob(ctx, req.(*GetAsyncJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListAsyncJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAsyncJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListAsyncJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListAsyncJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListAsyncJobs(ctx, req.(*ListAsyncJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListAgentNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListAgentNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListAgentNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListAgentNotes(ctx, req.(*ListAgentNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetAgentNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetAgentNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetAgentNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetAgentNote(ctx, req.(*GetAgentNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_SaveAgentNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAgentNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).SaveAgentNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_SaveAgentNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).SaveAgentNote(ctx, req.(*SaveAgentNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DeleteAgentNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DeleteAgentNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DeleteAgentNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DeleteAgentNote(ctx, req.(*DeleteAgentNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_SetAgentNoteInContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentNoteInContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).SetAgentNoteInContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_SetAgentNoteInContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).SetAgentNoteInContext(ctx, req.(*SetAgentNoteInContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_WatchAsyncJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAsyncJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).WatchAsyncJob(m, &grpc.GenericServerStream[WatchAsyncJobRequest, WatchAsyncJobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchAsyncJobServer = grpc.ServerStreamingServer[WatchAsyncJobResponse]

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openotters.daemon.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Runtime_GetInfo_Handler,
		},
		{
			MethodName: "BuildAgent",
			Handler:    _Runtime_BuildAgent_Handler,
		},
		{
			MethodName: "BuildToolImage",
			Handler:    _Runtime_BuildToolImage_Handler,
		},
		{
			MethodName: "SaveAgentImage",
			Handler:    _Runtime_SaveAgentImage_Handler,
		},
		{
			MethodName: "PullAgentImage",
			Handler:    _Runtime_PullAgentImage_Handler,
		},
		{
			MethodName: "PushAgentImage",
			Handler:    _Runtime_PushAgentImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _Runtime_ListImages_Handler,
		},
		{
			MethodName: "RefreshImage",
			Handler:    _Runtime_RefreshImage_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _Runtime_RemoveImage_Handler,
		},
		{
			MethodName: "DescribeImage",
			Handler:    _Runtime_DescribeImage_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _Runtime_CreateAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _Runtime_ListAgents_Handler,
		},
		{
			MethodName: "StartAgent",
			Handler:    _Runtime_StartAgent_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Runtime_StopAgent_Handler,
		},
		{
			MethodName: "RemoveAgent",
			Handler:    _Runtime_RemoveAgent_Handler,
		},
		{
			MethodName: "ChatWithAgent",
			Handler:    _Runtime_ChatWithAgent_Handler,
		},
		{
			MethodName: "PromptObject",
			Handler:    _Runtime_PromptObject_Handler,
		},
		{
			MethodName: "ListSessionMessages",
			Handler:    _Runtime_ListSessionMessages_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Runtime_ListSessions_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Runtime_DeleteSession_Handler,
		},
		{
			MethodName: "GetAgentLogs",
			Handler:    _Runtime_GetAgentLogs_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Runtime_ListModels_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _Runtime_ListProviders_Handler,
		},
		{
			MethodName: "AddProvider",
			Handler:    _Runtime_AddProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _Runtime_UpdateProvider_Handler,
		},
		{
			MethodName: "RemoveProvider",
			Handler:    _Runtime_RemoveProvider_Handler,
		},
		{
			MethodName: "SubmitAsyncJob",
			Handler:    _Runtime_SubmitAsyncJob_Handler,
		},
		{
			MethodName: "CancelAsyncJob",
			Handler:    _Runtime_CancelAsyncJob_Handler,
		},
		{
			MethodName: "GetAsyncJob",
			Handler:    _Runtime_GetAsyncJob_Handler,
		},
		{
			MethodName: "ListAsyncJobs",
			Handler:    _Runtime_ListAsyncJobs_Handler,
		},
		{
			MethodName: "ListAgentNotes",
			Handler:    _Runtime_ListAgentNotes_Handler,
		},
		{
			MethodName: "GetAgentNote",
			Handler:    _Runtime_GetAgentNote_Handler,
		},
		{
			MethodName: "SaveAgentNote",
			Handler:    _Runtime_SaveAgentNote_Handler,
		},
		{
			MethodName: "DeleteAgentNote",
			Handler:    _Runtime_DeleteAgentNote_Handler,
		},
		{
			MethodName: "SetAgentNoteInContext",
			Handler:    _Runtime_SetAgentNoteInContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStreamWithAgent",
			Handler:       _Runtime_ChatStreamWithAgent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAsyncJob",
			Handler:       _Runtime_WatchAsyncJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/daemon.proto",
}
