// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/daemon.proto

package daemonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openotters/openotters/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RuntimeName is the fully-qualified name of the Runtime service.
	RuntimeName = "openotters.daemon.v1.Runtime"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RuntimeGetInfoProcedure is the fully-qualified name of the Runtime's GetInfo RPC.
	RuntimeGetInfoProcedure = "/openotters.daemon.v1.Runtime/GetInfo"
	// RuntimeBuildAgentProcedure is the fully-qualified name of the Runtime's BuildAgent RPC.
	RuntimeBuildAgentProcedure = "/openotters.daemon.v1.Runtime/BuildAgent"
	// RuntimeBuildToolImageProcedure is the fully-qualified name of the Runtime's BuildToolImage RPC.
	RuntimeBuildToolImageProcedure = "/openotters.daemon.v1.Runtime/BuildToolImage"
	// RuntimeSaveAgentImageProcedure is the fully-qualified name of the Runtime's SaveAgentImage RPC.
	RuntimeSaveAgentImageProcedure = "/openotters.daemon.v1.Runtime/SaveAgentImage"
	// RuntimePullAgentImageProcedure is the fully-qualified name of the Runtime's PullAgentImage RPC.
	RuntimePullAgentImageProcedure = "/openotters.daemon.v1.Runtime/PullAgentImage"
	// RuntimePushAgentImageProcedure is the fully-qualified name of the Runtime's PushAgentImage RPC.
	RuntimePushAgentImageProcedure = "/openotters.daemon.v1.Runtime/PushAgentImage"
	// RuntimeListImagesProcedure is the fully-qualified name of the Runtime's ListImages RPC.
	RuntimeListImagesProcedure = "/openotters.daemon.v1.Runtime/ListImages"
	// RuntimeRefreshImagesProcedure is the fully-qualified name of the Runtime's RefreshImages RPC.
	RuntimeRefreshImagesProcedure = "/openotters.daemon.v1.Runtime/RefreshImages"
	// RuntimeRemoveImageProcedure is the fully-qualified name of the Runtime's RemoveImage RPC.
	RuntimeRemoveImageProcedure = "/openotters.daemon.v1.Runtime/RemoveImage"
	// RuntimeDescribeImageProcedure is the fully-qualified name of the Runtime's DescribeImage RPC.
	RuntimeDescribeImageProcedure = "/openotters.daemon.v1.Runtime/DescribeImage"
	// RuntimeCreateAgentProcedure is the fully-qualified name of the Runtime's CreateAgent RPC.
	RuntimeCreateAgentProcedure = "/openotters.daemon.v1.Runtime/CreateAgent"
	// RuntimeListAgentsProcedure is the fully-qualified name of the Runtime's ListAgents RPC.
	RuntimeListAgentsProcedure = "/openotters.daemon.v1.Runtime/ListAgents"
	// RuntimeStartAgentProcedure is the fully-qualified name of the Runtime's StartAgent RPC.
	RuntimeStartAgentProcedure = "/openotters.daemon.v1.Runtime/StartAgent"
	// RuntimeStopAgentProcedure is the fully-qualified name of the Runtime's StopAgent RPC.
	RuntimeStopAgentProcedure = "/openotters.daemon.v1.Runtime/StopAgent"
	// RuntimeRemoveAgentProcedure is the fully-qualified name of the Runtime's RemoveAgent RPC.
	RuntimeRemoveAgentProcedure = "/openotters.daemon.v1.Runtime/RemoveAgent"
	// RuntimeChatWithAgentProcedure is the fully-qualified name of the Runtime's ChatWithAgent RPC.
	RuntimeChatWithAgentProcedure = "/openotters.daemon.v1.Runtime/ChatWithAgent"
	// RuntimePromptObjectProcedure is the fully-qualified name of the Runtime's PromptObject RPC.
	RuntimePromptObjectProcedure = "/openotters.daemon.v1.Runtime/PromptObject"
	// RuntimeChatStreamWithAgentProcedure is the fully-qualified name of the Runtime's
	// ChatStreamWithAgent RPC.
	RuntimeChatStreamWithAgentProcedure = "/openotters.daemon.v1.Runtime/ChatStreamWithAgent"
	// RuntimeListSessionMessagesProcedure is the fully-qualified name of the Runtime's
	// ListSessionMessages RPC.
	RuntimeListSessionMessagesProcedure = "/openotters.daemon.v1.Runtime/ListSessionMessages"
	// RuntimeGetAgentLogsProcedure is the fully-qualified name of the Runtime's GetAgentLogs RPC.
	RuntimeGetAgentLogsProcedure = "/openotters.daemon.v1.Runtime/GetAgentLogs"
	// RuntimeListModelsProcedure is the fully-qualified name of the Runtime's ListModels RPC.
	RuntimeListModelsProcedure = "/openotters.daemon.v1.Runtime/ListModels"
	// RuntimeListProvidersProcedure is the fully-qualified name of the Runtime's ListProviders RPC.
	RuntimeListProvidersProcedure = "/openotters.daemon.v1.Runtime/ListProviders"
	// RuntimeAddProviderProcedure is the fully-qualified name of the Runtime's AddProvider RPC.
	RuntimeAddProviderProcedure = "/openotters.daemon.v1.Runtime/AddProvider"
	// RuntimeUpdateProviderProcedure is the fully-qualified name of the Runtime's UpdateProvider RPC.
	RuntimeUpdateProviderProcedure = "/openotters.daemon.v1.Runtime/UpdateProvider"
	// RuntimeRemoveProviderProcedure is the fully-qualified name of the Runtime's RemoveProvider RPC.
	RuntimeRemoveProviderProcedure = "/openotters.daemon.v1.Runtime/RemoveProvider"
)

// RuntimeClient is a client for the openotters.daemon.v1.Runtime service.
type RuntimeClient interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	BuildAgent(context.Context, *connect.Request[v1.BuildAgentRequest]) (*connect.Response[v1.BuildAgentResponse], error)
	BuildToolImage(context.Context, *connect.Request[v1.BuildToolImageRequest]) (*connect.Response[v1.BuildToolImageResponse], error)
	SaveAgentImage(context.Context, *connect.Request[v1.SaveAgentImageRequest]) (*connect.Response[v1.SaveAgentImageResponse], error)
	PullAgentImage(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error)
	PushAgentImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error)
	ListImages(context.Context, *connect.Request[v1.ListImagesRequest]) (*connect.Response[v1.ListImagesResponse], error)
	RefreshImages(context.Context, *connect.Request[v1.RefreshImagesRequest]) (*connect.Response[v1.RefreshImagesResponse], error)
	RemoveImage(context.Context, *connect.Request[v1.RemoveImageRequest]) (*connect.Response[v1.RemoveImageResponse], error)
	DescribeImage(context.Context, *connect.Request[v1.DescribeImageRequest]) (*connect.Response[v1.DescribeImageResponse], error)
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[v1.StartAgentResponse], error)
	StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[v1.StopAgentResponse], error)
	RemoveAgent(context.Context, *connect.Request[v1.RemoveAgentRequest]) (*connect.Response[v1.RemoveAgentResponse], error)
	ChatWithAgent(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error)
	PromptObject(context.Context, *connect.Request[v1.PromptObjectRequest]) (*connect.Response[v1.PromptObjectResponse], error)
	ChatStreamWithAgent(context.Context, *connect.Request[v1.ChatStreamRequest]) (*connect.ServerStreamForClient[v1.ChatStreamEvent], error)
	ListSessionMessages(context.Context, *connect.Request[v1.ListSessionMessagesRequest]) (*connect.Response[v1.ListSessionMessagesResponse], error)
	GetAgentLogs(context.Context, *connect.Request[v1.GetAgentLogsRequest]) (*connect.Response[v1.GetAgentLogsResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	AddProvider(context.Context, *connect.Request[v1.AddProviderRequest]) (*connect.Response[v1.AddProviderResponse], error)
	UpdateProvider(context.Context, *connect.Request[v1.UpdateProviderRequest]) (*connect.Response[v1.UpdateProviderResponse], error)
	RemoveProvider(context.Context, *connect.Request[v1.RemoveProviderRequest]) (*connect.Response[v1.RemoveProviderResponse], error)
}

// NewRuntimeClient constructs a client for the openotters.daemon.v1.Runtime service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRuntimeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RuntimeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runtimeMethods := v1.File_v1_daemon_proto.Services().ByName("Runtime").Methods()
	return &runtimeClient{
		getInfo: connect.NewClient[v1.GetInfoRequest, v1.GetInfoResponse](
			httpClient,
			baseURL+RuntimeGetInfoProcedure,
			connect.WithSchema(runtimeMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
		buildAgent: connect.NewClient[v1.BuildAgentRequest, v1.BuildAgentResponse](
			httpClient,
			baseURL+RuntimeBuildAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("BuildAgent")),
			connect.WithClientOptions(opts...),
		),
		buildToolImage: connect.NewClient[v1.BuildToolImageRequest, v1.BuildToolImageResponse](
			httpClient,
			baseURL+RuntimeBuildToolImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("BuildToolImage")),
			connect.WithClientOptions(opts...),
		),
		saveAgentImage: connect.NewClient[v1.SaveAgentImageRequest, v1.SaveAgentImageResponse](
			httpClient,
			baseURL+RuntimeSaveAgentImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("SaveAgentImage")),
			connect.WithClientOptions(opts...),
		),
		pullAgentImage: connect.NewClient[v1.PullRequest, v1.PullResponse](
			httpClient,
			baseURL+RuntimePullAgentImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("PullAgentImage")),
			connect.WithClientOptions(opts...),
		),
		pushAgentImage: connect.NewClient[v1.PushRequest, v1.PushResponse](
			httpClient,
			baseURL+RuntimePushAgentImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("PushAgentImage")),
			connect.WithClientOptions(opts...),
		),
		listImages: connect.NewClient[v1.ListImagesRequest, v1.ListImagesResponse](
			httpClient,
			baseURL+RuntimeListImagesProcedure,
			connect.WithSchema(runtimeMethods.ByName("ListImages")),
			connect.WithClientOptions(opts...),
		),
		refreshImages: connect.NewClient[v1.RefreshImagesRequest, v1.RefreshImagesResponse](
			httpClient,
			baseURL+RuntimeRefreshImagesProcedure,
			connect.WithSchema(runtimeMethods.ByName("RefreshImages")),
			connect.WithClientOptions(opts...),
		),
		removeImage: connect.NewClient[v1.RemoveImageRequest, v1.RemoveImageResponse](
			httpClient,
			baseURL+RuntimeRemoveImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("RemoveImage")),
			connect.WithClientOptions(opts...),
		),
		describeImage: connect.NewClient[v1.DescribeImageRequest, v1.DescribeImageResponse](
			httpClient,
			baseURL+RuntimeDescribeImageProcedure,
			connect.WithSchema(runtimeMethods.ByName("DescribeImage")),
			connect.WithClientOptions(opts...),
		),
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.CreateAgentResponse](
			httpClient,
			baseURL+RuntimeCreateAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+RuntimeListAgentsProcedure,
			connect.WithSchema(runtimeMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		startAgent: connect.NewClient[v1.StartAgentRequest, v1.StartAgentResponse](
			httpClient,
			baseURL+RuntimeStartAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("StartAgent")),
			connect.WithClientOptions(opts...),
		),
		stopAgent: connect.NewClient[v1.StopAgentRequest, v1.StopAgentResponse](
			httpClient,
			baseURL+RuntimeStopAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("StopAgent")),
			connect.WithClientOptions(opts...),
		),
		removeAgent: connect.NewClient[v1.RemoveAgentRequest, v1.RemoveAgentResponse](
			httpClient,
			baseURL+RuntimeRemoveAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("RemoveAgent")),
			connect.WithClientOptions(opts...),
		),
		chatWithAgent: connect.NewClient[v1.ChatRequest, v1.ChatResponse](
			httpClient,
			baseURL+RuntimeChatWithAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("ChatWithAgent")),
			connect.WithClientOptions(opts...),
		),
		promptObject: connect.NewClient[v1.PromptObjectRequest, v1.PromptObjectResponse](
			httpClient,
			baseURL+RuntimePromptObjectProcedure,
			connect.WithSchema(runtimeMethods.ByName("PromptObject")),
			connect.WithClientOptions(opts...),
		),
		chatStreamWithAgent: connect.NewClient[v1.ChatStreamRequest, v1.ChatStreamEvent](
			httpClient,
			baseURL+RuntimeChatStreamWithAgentProcedure,
			connect.WithSchema(runtimeMethods.ByName("ChatStreamWithAgent")),
			connect.WithClientOptions(opts...),
		),
		listSessionMessages: connect.NewClient[v1.ListSessionMessagesRequest, v1.ListSessionMessagesResponse](
			httpClient,
			baseURL+RuntimeListSessionMessagesProcedure,
			connect.WithSchema(runtimeMethods.ByName("ListSessionMessages")),
			connect.WithClientOptions(opts...),
		),
		getAgentLogs: connect.NewClient[v1.GetAgentLogsRequest, v1.GetAgentLogsResponse](
			httpClient,
			baseURL+RuntimeGetAgentLogsProcedure,
			connect.WithSchema(runtimeMethods.ByName("GetAgentLogs")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+RuntimeListModelsProcedure,
			connect.WithSchema(runtimeMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+RuntimeListProvidersProcedure,
			connect.WithSchema(runtimeMethods.ByName("ListProviders")),
			connect.WithClientOptions(opts...),
		),
		addProvider: connect.NewClient[v1.AddProviderRequest, v1.AddProviderResponse](
			httpClient,
			baseURL+RuntimeAddProviderProcedure,
			connect.WithSchema(runtimeMethods.ByName("AddProvider")),
			connect.WithClientOptions(opts...),
		),
		updateProvider: connect.NewClient[v1.UpdateProviderRequest, v1.UpdateProviderResponse](
			httpClient,
			baseURL+RuntimeUpdateProviderProcedure,
			connect.WithSchema(runtimeMethods.ByName("UpdateProvider")),
			connect.WithClientOptions(opts...),
		),
		removeProvider: connect.NewClient[v1.RemoveProviderRequest, v1.RemoveProviderResponse](
			httpClient,
			baseURL+RuntimeRemoveProviderProcedure,
			connect.WithSchema(runtimeMethods.ByName("RemoveProvider")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runtimeClient implements RuntimeClient.
type runtimeClient struct {
	getInfo             *connect.Client[v1.GetInfoRequest, v1.GetInfoResponse]
	buildAgent          *connect.Client[v1.BuildAgentRequest, v1.BuildAgentResponse]
	buildToolImage      *connect.Client[v1.BuildToolImageRequest, v1.BuildToolImageResponse]
	saveAgentImage      *connect.Client[v1.SaveAgentImageRequest, v1.SaveAgentImageResponse]
	pullAgentImage      *connect.Client[v1.PullRequest, v1.PullResponse]
	pushAgentImage      *connect.Client[v1.PushRequest, v1.PushResponse]
	listImages          *connect.Client[v1.ListImagesRequest, v1.ListImagesResponse]
	refreshImages       *connect.Client[v1.RefreshImagesRequest, v1.RefreshImagesResponse]
	removeImage         *connect.Client[v1.RemoveImageRequest, v1.RemoveImageResponse]
	describeImage       *connect.Client[v1.DescribeImageRequest, v1.DescribeImageResponse]
	createAgent         *connect.Client[v1.CreateAgentRequest, v1.CreateAgentResponse]
	listAgents          *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	startAgent          *connect.Client[v1.StartAgentRequest, v1.StartAgentResponse]
	stopAgent           *connect.Client[v1.StopAgentRequest, v1.StopAgentResponse]
	removeAgent         *connect.Client[v1.RemoveAgentRequest, v1.RemoveAgentResponse]
	chatWithAgent       *connect.Client[v1.ChatRequest, v1.ChatResponse]
	promptObject        *connect.Client[v1.PromptObjectRequest, v1.PromptObjectResponse]
	chatStreamWithAgent *connect.Client[v1.ChatStreamRequest, v1.ChatStreamEvent]
	listSessionMessages *connect.Client[v1.ListSessionMessagesRequest, v1.ListSessionMessagesResponse]
	getAgentLogs        *connect.Client[v1.GetAgentLogsRequest, v1.GetAgentLogsResponse]
	listModels          *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	listProviders       *connect.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	addProvider         *connect.Client[v1.AddProviderRequest, v1.AddProviderResponse]
	updateProvider      *connect.Client[v1.UpdateProviderRequest, v1.UpdateProviderResponse]
	removeProvider      *connect.Client[v1.RemoveProviderRequest, v1.RemoveProviderResponse]
}

// GetInfo calls openotters.daemon.v1.Runtime.GetInfo.
func (c *runtimeClient) GetInfo(ctx context.Context, req *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// BuildAgent calls openotters.daemon.v1.Runtime.BuildAgent.
func (c *runtimeClient) BuildAgent(ctx context.Context, req *connect.Request[v1.BuildAgentRequest]) (*connect.Response[v1.BuildAgentResponse], error) {
	return c.buildAgent.CallUnary(ctx, req)
}

// BuildToolImage calls openotters.daemon.v1.Runtime.BuildToolImage.
func (c *runtimeClient) BuildToolImage(ctx context.Context, req *connect.Request[v1.BuildToolImageRequest]) (*connect.Response[v1.BuildToolImageResponse], error) {
	return c.buildToolImage.CallUnary(ctx, req)
}

// SaveAgentImage calls openotters.daemon.v1.Runtime.SaveAgentImage.
func (c *runtimeClient) SaveAgentImage(ctx context.Context, req *connect.Request[v1.SaveAgentImageRequest]) (*connect.Response[v1.SaveAgentImageResponse], error) {
	return c.saveAgentImage.CallUnary(ctx, req)
}

// PullAgentImage calls openotters.daemon.v1.Runtime.PullAgentImage.
func (c *runtimeClient) PullAgentImage(ctx context.Context, req *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error) {
	return c.pullAgentImage.CallUnary(ctx, req)
}

// PushAgentImage calls openotters.daemon.v1.Runtime.PushAgentImage.
func (c *runtimeClient) PushAgentImage(ctx context.Context, req *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error) {
	return c.pushAgentImage.CallUnary(ctx, req)
}

// ListImages calls openotters.daemon.v1.Runtime.ListImages.
func (c *runtimeClient) ListImages(ctx context.Context, req *connect.Request[v1.ListImagesRequest]) (*connect.Response[v1.ListImagesResponse], error) {
	return c.listImages.CallUnary(ctx, req)
}

// RefreshImages calls openotters.daemon.v1.Runtime.RefreshImages.
func (c *runtimeClient) RefreshImages(ctx context.Context, req *connect.Request[v1.RefreshImagesRequest]) (*connect.Response[v1.RefreshImagesResponse], error) {
	return c.refreshImages.CallUnary(ctx, req)
}

// RemoveImage calls openotters.daemon.v1.Runtime.RemoveImage.
func (c *runtimeClient) RemoveImage(ctx context.Context, req *connect.Request[v1.RemoveImageRequest]) (*connect.Response[v1.RemoveImageResponse], error) {
	return c.removeImage.CallUnary(ctx, req)
}

// DescribeImage calls openotters.daemon.v1.Runtime.DescribeImage.
func (c *runtimeClient) DescribeImage(ctx context.Context, req *connect.Request[v1.DescribeImageRequest]) (*connect.Response[v1.DescribeImageResponse], error) {
	return c.describeImage.CallUnary(ctx, req)
}

// CreateAgent calls openotters.daemon.v1.Runtime.CreateAgent.
func (c *runtimeClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// ListAgents calls openotters.daemon.v1.Runtime.ListAgents.
func (c *runtimeClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// StartAgent calls openotters.daemon.v1.Runtime.StartAgent.
func (c *runtimeClient) StartAgent(ctx context.Context, req *connect.Request[v1.StartAgentRequest]) (*connect.Response[v1.StartAgentResponse], error) {
	return c.startAgent.CallUnary(ctx, req)
}

// StopAgent calls openotters.daemon.v1.Runtime.StopAgent.
func (c *runtimeClient) StopAgent(ctx context.Context, req *connect.Request[v1.StopAgentRequest]) (*connect.Response[v1.StopAgentResponse], error) {
	return c.stopAgent.CallUnary(ctx, req)
}

// RemoveAgent calls openotters.daemon.v1.Runtime.RemoveAgent.
func (c *runtimeClient) RemoveAgent(ctx context.Context, req *connect.Request[v1.RemoveAgentRequest]) (*connect.Response[v1.RemoveAgentResponse], error) {
	return c.removeAgent.CallUnary(ctx, req)
}

// ChatWithAgent calls openotters.daemon.v1.Runtime.ChatWithAgent.
func (c *runtimeClient) ChatWithAgent(ctx context.Context, req *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error) {
	return c.chatWithAgent.CallUnary(ctx, req)
}

// PromptObject calls openotters.daemon.v1.Runtime.PromptObject.
func (c *runtimeClient) PromptObject(ctx context.Context, req *connect.Request[v1.PromptObjectRequest]) (*connect.Response[v1.PromptObjectResponse], error) {
	return c.promptObject.CallUnary(ctx, req)
}

// ChatStreamWithAgent calls openotters.daemon.v1.Runtime.ChatStreamWithAgent.
func (c *runtimeClient) ChatStreamWithAgent(ctx context.Context, req *connect.Request[v1.ChatStreamRequest]) (*connect.ServerStreamForClient[v1.ChatStreamEvent], error) {
	return c.chatStreamWithAgent.CallServerStream(ctx, req)
}

// ListSessionMessages calls openotters.daemon.v1.Runtime.ListSessionMessages.
func (c *runtimeClient) ListSessionMessages(ctx context.Context, req *connect.Request[v1.ListSessionMessagesRequest]) (*connect.Response[v1.ListSessionMessagesResponse], error) {
	return c.listSessionMessages.CallUnary(ctx, req)
}

// GetAgentLogs calls openotters.daemon.v1.Runtime.GetAgentLogs.
func (c *runtimeClient) GetAgentLogs(ctx context.Context, req *connect.Request[v1.GetAgentLogsRequest]) (*connect.Response[v1.GetAgentLogsResponse], error) {
	return c.getAgentLogs.CallUnary(ctx, req)
}

// ListModels calls openotters.daemon.v1.Runtime.ListModels.
func (c *runtimeClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// ListProviders calls openotters.daemon.v1.Runtime.ListProviders.
func (c *runtimeClient) ListProviders(ctx context.Context, req *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// AddProvider calls openotters.daemon.v1.Runtime.AddProvider.
func (c *runtimeClient) AddProvider(ctx context.Context, req *connect.Request[v1.AddProviderRequest]) (*connect.Response[v1.AddProviderResponse], error) {
	return c.addProvider.CallUnary(ctx, req)
}

// UpdateProvider calls openotters.daemon.v1.Runtime.UpdateProvider.
func (c *runtimeClient) UpdateProvider(ctx context.Context, req *connect.Request[v1.UpdateProviderRequest]) (*connect.Response[v1.UpdateProviderResponse], error) {
	return c.updateProvider.CallUnary(ctx, req)
}

// RemoveProvider calls openotters.daemon.v1.Runtime.RemoveProvider.
func (c *runtimeClient) RemoveProvider(ctx context.Context, req *connect.Request[v1.RemoveProviderRequest]) (*connect.Response[v1.RemoveProviderResponse], error) {
	return c.removeProvider.CallUnary(ctx, req)
}

// RuntimeHandler is an implementation of the openotters.daemon.v1.Runtime service.
type RuntimeHandler interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	BuildAgent(context.Context, *connect.Request[v1.BuildAgentRequest]) (*connect.Response[v1.BuildAgentResponse], error)
	BuildToolImage(context.Context, *connect.Request[v1.BuildToolImageRequest]) (*connect.Response[v1.BuildToolImageResponse], error)
	SaveAgentImage(context.Context, *connect.Request[v1.SaveAgentImageRequest]) (*connect.Response[v1.SaveAgentImageResponse], error)
	PullAgentImage(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error)
	PushAgentImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error)
	ListImages(context.Context, *connect.Request[v1.ListImagesRequest]) (*connect.Response[v1.ListImagesResponse], error)
	RefreshImages(context.Context, *connect.Request[v1.RefreshImagesRequest]) (*connect.Response[v1.RefreshImagesResponse], error)
	RemoveImage(context.Context, *connect.Request[v1.RemoveImageRequest]) (*connect.Response[v1.RemoveImageResponse], error)
	DescribeImage(context.Context, *connect.Request[v1.DescribeImageRequest]) (*connect.Response[v1.DescribeImageResponse], error)
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[v1.StartAgentResponse], error)
	StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[v1.StopAgentResponse], error)
	RemoveAgent(context.Context, *connect.Request[v1.RemoveAgentRequest]) (*connect.Response[v1.RemoveAgentResponse], error)
	ChatWithAgent(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error)
	PromptObject(context.Context, *connect.Request[v1.PromptObjectRequest]) (*connect.Response[v1.PromptObjectResponse], error)
	ChatStreamWithAgent(context.Context, *connect.Request[v1.ChatStreamRequest], *connect.ServerStream[v1.ChatStreamEvent]) error
	ListSessionMessages(context.Context, *connect.Request[v1.ListSessionMessagesRequest]) (*connect.Response[v1.ListSessionMessagesResponse], error)
	GetAgentLogs(context.Context, *connect.Request[v1.GetAgentLogsRequest]) (*connect.Response[v1.GetAgentLogsResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	AddProvider(context.Context, *connect.Request[v1.AddProviderRequest]) (*connect.Response[v1.AddProviderResponse], error)
	UpdateProvider(context.Context, *connect.Request[v1.UpdateProviderRequest]) (*connect.Response[v1.UpdateProviderResponse], error)
	RemoveProvider(context.Context, *connect.Request[v1.RemoveProviderRequest]) (*connect.Response[v1.RemoveProviderResponse], error)
}

// NewRuntimeHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRuntimeHandler(svc RuntimeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runtimeMethods := v1.File_v1_daemon_proto.Services().ByName("Runtime").Methods()
	runtimeGetInfoHandler := connect.NewUnaryHandler(
		RuntimeGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(runtimeMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeBuildAgentHandler := connect.NewUnaryHandler(
		RuntimeBuildAgentProcedure,
		svc.BuildAgent,
		connect.WithSchema(runtimeMethods.ByName("BuildAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeBuildToolImageHandler := connect.NewUnaryHandler(
		RuntimeBuildToolImageProcedure,
		svc.BuildToolImage,
		connect.WithSchema(runtimeMethods.ByName("BuildToolImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeSaveAgentImageHandler := connect.NewUnaryHandler(
		RuntimeSaveAgentImageProcedure,
		svc.SaveAgentImage,
		connect.WithSchema(runtimeMethods.ByName("SaveAgentImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimePullAgentImageHandler := connect.NewUnaryHandler(
		RuntimePullAgentImageProcedure,
		svc.PullAgentImage,
		connect.WithSchema(runtimeMethods.ByName("PullAgentImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimePushAgentImageHandler := connect.NewUnaryHandler(
		RuntimePushAgentImageProcedure,
		svc.PushAgentImage,
		connect.WithSchema(runtimeMethods.ByName("PushAgentImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeListImagesHandler := connect.NewUnaryHandler(
		RuntimeListImagesProcedure,
		svc.ListImages,
		connect.WithSchema(runtimeMethods.ByName("ListImages")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeRefreshImagesHandler := connect.NewUnaryHandler(
		RuntimeRefreshImagesProcedure,
		svc.RefreshImages,
		connect.WithSchema(runtimeMethods.ByName("RefreshImages")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeRemoveImageHandler := connect.NewUnaryHandler(
		RuntimeRemoveImageProcedure,
		svc.RemoveImage,
		connect.WithSchema(runtimeMethods.ByName("RemoveImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeDescribeImageHandler := connect.NewUnaryHandler(
		RuntimeDescribeImageProcedure,
		svc.DescribeImage,
		connect.WithSchema(runtimeMethods.ByName("DescribeImage")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeCreateAgentHandler := connect.NewUnaryHandler(
		RuntimeCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(runtimeMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeListAgentsHandler := connect.NewUnaryHandler(
		RuntimeListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(runtimeMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeStartAgentHandler := connect.NewUnaryHandler(
		RuntimeStartAgentProcedure,
		svc.StartAgent,
		connect.WithSchema(runtimeMethods.ByName("StartAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeStopAgentHandler := connect.NewUnaryHandler(
		RuntimeStopAgentProcedure,
		svc.StopAgent,
		connect.WithSchema(runtimeMethods.ByName("StopAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeRemoveAgentHandler := connect.NewUnaryHandler(
		RuntimeRemoveAgentProcedure,
		svc.RemoveAgent,
		connect.WithSchema(runtimeMethods.ByName("RemoveAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeChatWithAgentHandler := connect.NewUnaryHandler(
		RuntimeChatWithAgentProcedure,
		svc.ChatWithAgent,
		connect.WithSchema(runtimeMethods.ByName("ChatWithAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimePromptObjectHandler := connect.NewUnaryHandler(
		RuntimePromptObjectProcedure,
		svc.PromptObject,
		connect.WithSchema(runtimeMethods.ByName("PromptObject")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeChatStreamWithAgentHandler := connect.NewServerStreamHandler(
		RuntimeChatStreamWithAgentProcedure,
		svc.ChatStreamWithAgent,
		connect.WithSchema(runtimeMethods.ByName("ChatStreamWithAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeListSessionMessagesHandler := connect.NewUnaryHandler(
		RuntimeListSessionMessagesProcedure,
		svc.ListSessionMessages,
		connect.WithSchema(runtimeMethods.ByName("ListSessionMessages")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeGetAgentLogsHandler := connect.NewUnaryHandler(
		RuntimeGetAgentLogsProcedure,
		svc.GetAgentLogs,
		connect.WithSchema(runtimeMethods.ByName("GetAgentLogs")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeListModelsHandler := connect.NewUnaryHandler(
		RuntimeListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(runtimeMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeListProvidersHandler := connect.NewUnaryHandler(
		RuntimeListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(runtimeMethods.ByName("ListProviders")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeAddProviderHandler := connect.NewUnaryHandler(
		RuntimeAddProviderProcedure,
		svc.AddProvider,
		connect.WithSchema(runtimeMethods.ByName("AddProvider")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeUpdateProviderHandler := connect.NewUnaryHandler(
		RuntimeUpdateProviderProcedure,
		svc.UpdateProvider,
		connect.WithSchema(runtimeMethods.ByName("UpdateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeRemoveProviderHandler := connect.NewUnaryHandler(
		RuntimeRemoveProviderProcedure,
		svc.RemoveProvider,
		connect.WithSchema(runtimeMethods.ByName("RemoveProvider")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openotters.daemon.v1.Runtime/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RuntimeGetInfoProcedure:
			runtimeGetInfoHandler.ServeHTTP(w, r)
		case RuntimeBuildAgentProcedure:
			runtimeBuildAgentHandler.ServeHTTP(w, r)
		case RuntimeBuildToolImageProcedure:
			runtimeBuildToolImageHandler.ServeHTTP(w, r)
		case RuntimeSaveAgentImageProcedure:
			runtimeSaveAgentImageHandler.ServeHTTP(w, r)
		case RuntimePullAgentImageProcedure:
			runtimePullAgentImageHandler.ServeHTTP(w, r)
		case RuntimePushAgentImageProcedure:
			runtimePushAgentImageHandler.ServeHTTP(w, r)
		case RuntimeListImagesProcedure:
			runtimeListImagesHandler.ServeHTTP(w, r)
		case RuntimeRefreshImagesProcedure:
			runtimeRefreshImagesHandler.ServeHTTP(w, r)
		case RuntimeRemoveImageProcedure:
			runtimeRemoveImageHandler.ServeHTTP(w, r)
		case RuntimeDescribeImageProcedure:
			runtimeDescribeImageHandler.ServeHTTP(w, r)
		case RuntimeCreateAgentProcedure:
			runtimeCreateAgentHandler.ServeHTTP(w, r)
		case RuntimeListAgentsProcedure:
			runtimeListAgentsHandler.ServeHTTP(w, r)
		case RuntimeStartAgentProcedure:
			runtimeStartAgentHandler.ServeHTTP(w, r)
		case RuntimeStopAgentProcedure:
			runtimeStopAgentHandler.ServeHTTP(w, r)
		case RuntimeRemoveAgentProcedure:
			runtimeRemoveAgentHandler.ServeHTTP(w, r)
		case RuntimeChatWithAgentProcedure:
			runtimeChatWithAgentHandler.ServeHTTP(w, r)
		case RuntimePromptObjectProcedure:
			runtimePromptObjectHandler.ServeHTTP(w, r)
		case RuntimeChatStreamWithAgentProcedure:
			runtimeChatStreamWithAgentHandler.ServeHTTP(w, r)
		case RuntimeListSessionMessagesProcedure:
			runtimeListSessionMessagesHandler.ServeHTTP(w, r)
		case RuntimeGetAgentLogsProcedure:
			runtimeGetAgentLogsHandler.ServeHTTP(w, r)
		case RuntimeListModelsProcedure:
			runtimeListModelsHandler.ServeHTTP(w, r)
		case RuntimeListProvidersProcedure:
			runtimeListProvidersHandler.ServeHTTP(w, r)
		case RuntimeAddProviderProcedure:
			runtimeAddProviderHandler.ServeHTTP(w, r)
		case RuntimeUpdateProviderProcedure:
			runtimeUpdateProviderHandler.ServeHTTP(w, r)
		case RuntimeRemoveProviderProcedure:
			runtimeRemoveProviderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRuntimeHandler returns CodeUnimplemented from all methods.
type UnimplementedRuntimeHandler struct{}

func (UnimplementedRuntimeHandler) GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.GetInfo is not implemented"))
}

func (UnimplementedRuntimeHandler) BuildAgent(context.Context, *connect.Request[v1.BuildAgentRequest]) (*connect.Response[v1.BuildAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.BuildAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) BuildToolImage(context.Context, *connect.Request[v1.BuildToolImageRequest]) (*connect.Response[v1.BuildToolImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.BuildToolImage is not implemented"))
}

func (UnimplementedRuntimeHandler) SaveAgentImage(context.Context, *connect.Request[v1.SaveAgentImageRequest]) (*connect.Response[v1.SaveAgentImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.SaveAgentImage is not implemented"))
}

func (UnimplementedRuntimeHandler) PullAgentImage(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.PullAgentImage is not implemented"))
}

func (UnimplementedRuntimeHandler) PushAgentImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.PushAgentImage is not implemented"))
}

func (UnimplementedRuntimeHandler) ListImages(context.Context, *connect.Request[v1.ListImagesRequest]) (*connect.Response[v1.ListImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ListImages is not implemented"))
}

func (UnimplementedRuntimeHandler) RefreshImages(context.Context, *connect.Request[v1.RefreshImagesRequest]) (*connect.Response[v1.RefreshImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.RefreshImages is not implemented"))
}

func (UnimplementedRuntimeHandler) RemoveImage(context.Context, *connect.Request[v1.RemoveImageRequest]) (*connect.Response[v1.RemoveImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.RemoveImage is not implemented"))
}

func (UnimplementedRuntimeHandler) DescribeImage(context.Context, *connect.Request[v1.DescribeImageRequest]) (*connect.Response[v1.DescribeImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.DescribeImage is not implemented"))
}

func (UnimplementedRuntimeHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.CreateAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ListAgents is not implemented"))
}

func (UnimplementedRuntimeHandler) StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[v1.StartAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.StartAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[v1.StopAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.StopAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) RemoveAgent(context.Context, *connect.Request[v1.RemoveAgentRequest]) (*connect.Response[v1.RemoveAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.RemoveAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) ChatWithAgent(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ChatWithAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) PromptObject(context.Context, *connect.Request[v1.PromptObjectRequest]) (*connect.Response[v1.PromptObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.PromptObject is not implemented"))
}

func (UnimplementedRuntimeHandler) ChatStreamWithAgent(context.Context, *connect.Request[v1.ChatStreamRequest], *connect.ServerStream[v1.ChatStreamEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ChatStreamWithAgent is not implemented"))
}

func (UnimplementedRuntimeHandler) ListSessionMessages(context.Context, *connect.Request[v1.ListSessionMessagesRequest]) (*connect.Response[v1.ListSessionMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ListSessionMessages is not implemented"))
}

func (UnimplementedRuntimeHandler) GetAgentLogs(context.Context, *connect.Request[v1.GetAgentLogsRequest]) (*connect.Response[v1.GetAgentLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.GetAgentLogs is not implemented"))
}

func (UnimplementedRuntimeHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ListModels is not implemented"))
}

func (UnimplementedRuntimeHandler) ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.ListProviders is not implemented"))
}

func (UnimplementedRuntimeHandler) AddProvider(context.Context, *connect.Request[v1.AddProviderRequest]) (*connect.Response[v1.AddProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.AddProvider is not implemented"))
}

func (UnimplementedRuntimeHandler) UpdateProvider(context.Context, *connect.Request[v1.UpdateProviderRequest]) (*connect.Response[v1.UpdateProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.UpdateProvider is not implemented"))
}

func (UnimplementedRuntimeHandler) RemoveProvider(context.Context, *connect.Request[v1.RemoveProviderRequest]) (*connect.Response[v1.RemoveProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openotters.daemon.v1.Runtime.RemoveProvider is not implemented"))
}
